name: eCommerce
description: "A Flutter-based eCommerce application that features user authentication powered by Firebase Authentication (email & password login/registration). Product data and other related content are fetched using the FakeStore API, providing a realistic shopping experience. The app includes modern UI components, a bottom navigation bar, and dynamic product detail views. It serves as a practical full-stack demo combining real-time authentication with a mock commerce backend."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  firebase_auth: ^5.5.3
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

